name: rtsp-test-server
base: core22
version: git
summary: Simple server providing some test rtsp streams
description: |
  Based on GStreamer RTSP Server.

  **Config file location:** /var/snap/rtsp-test-server/common/rtsp-test-server.conf

  **Available urls:**
  * rtsp://localhost:8554/bars
  * rtsp://localhost:8554/white
  * rtsp://localhost:8554/black
  * rtsp://localhost:8554/red
  * rtsp://localhost:8554/green
  * rtsp://localhost:8554/blue
  * rtsp://localhost:8554/bars-vp8
  * rtsp://localhost:8554/white-vp8
  * rtsp://localhost:8554/black-vp8
  * rtsp://localhost:8554/red-vp8
  * rtsp://localhost:8554/green-vp8
  * rtsp://localhost:8554/blue-vp8
license: GPL-3.0
grade: stable
confinement: strict

architectures:
  - build-on: amd64
#  - build-on: armhf
  - build-on: arm64

environment:
  GST_DEBUG: 3
  GST_DEBUG_NO_COLOR: 1
  GST_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
  GST_PLUGIN_SCANNER: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner

parts:
  server:
    plugin: cmake
    source: https://github.com/RSATom/rtsp-test-server.git
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    build-packages:
      - g++
      - make
      - libfmt-dev
      - libspdlog-dev
      - libconfig-dev
      - libgstreamer1.0-dev
      - libgstrtspserver-1.0-dev
    stage-packages:
      - libgstrtspserver-1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libslang2
      - libgpm2
      - libconfig9
      - libspdlog1

apps:
  rtsp-test-server:
    command: opt/${SNAPCRAFT_PROJECT_NAME}/bin/rtsp-test-server
    daemon: simple
    plugs:
      - network-bind
      - network
